Fail the dockerfile build if dagster-cloud is not included in the built image (#29423)
Build this dockerfile before and after uv add dagster-cloud

> Insert changelog entry or delete this section.

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

diff --git a/python_modules/libraries/dagster-dg/dagster_dg/templates/deploy_uv_editable_Dockerfile.jinja b/python_modules/libraries/dagster-dg/dagster_dg/templates/deploy_uv_editable_Dockerfile.jinja
--- a/python_modules/libraries/dagster-dg/dagster_dg/templates/deploy_uv_editable_Dockerfile.jinja
+++ b/python_modules/libraries/dagster-dg/dagster_dg/templates/deploy_uv_editable_Dockerfile.jinja
@@ -41,3 +41,9 @@ COPY --from=builder /dagster-internal /dagster-internal
 ENV PATH="/app/.venv/bin:$PATH"
 
 WORKDIR /app
+
+# Make sure dagster-cloud is installed. Fail early here if not.
+RUN if ! dagster-cloud --version; then \
+        echo "Could not find the dagster-cloud package.  Make sure you include the dagster-cloud package in your project."; \
+        exit 1; \
+    fi
